/**
 * Auto-generated from real ES records for the top GA-viewed artworks.
 * Source: scripts/fetch-top-artworks.ts → scripts/transform-to-sample.ts
 * Generated: 2026-05-05T13:10:44.221Z
 *
 * Do not hand-edit. Regenerate by re-running the scripts.
 */

import type { SampleObject } from "./sample-data";

export const topViewedObjects: SampleObject[] = [
	// GA views (90d): 11979 — /artworks/isabella-and-the-pot-of-basil
	{
		id: `141937`,
		title: `Isabella and the Pot of Basil`,
		artist: `William Holman Hunt`,
		artistDates: `English, 1827–1910`,
		artistNationality: `English`,
		constituents: [
			{
				id: `C-15960`,
				name: `William Holman Hunt`,
				role: `Artist`,
				dates: `English, 1827–1910`,
				nationality: `English`,
			},
		],
		date: `1867–1868`,
		dateBegin: 1867,
		dateEnd: 1868,
		medium: `Oil on canvas`,
		dimensions: `Overall: 23 11/16 x 15 3/16 in. (60.2 x 38.6 cm) Framed: 32 11/16 x 24 1/16 in. (83.026 x 61.119 cm)`,
		creditLine: `Museum purchase, Yvonne Cappeller 1992 Trust Fund, Grover A. Magnin Endowment Bequest Income Fund, Roscoe and Margaret Oakes Endowment Income Fund, and generous donations from Lucy Young Hamilton, Margaret and William R. Hearst III, Jessica and Jason Moment, Lisa Sardegna and David Carrillo, and Diane B. Wilsey`,
		accession: `2021.31`,
		accessionDate: `2021`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: false,
		labelText: `In 1848, seven young English artists formed a secret artistic alliance. Calling themselves the Pre-Raphaelite Brotherhood (PRB), the artists, including William Holman Hunt, Dante Gabriel Rossetti, and John Everett Millais, defined a new visual language of truth and beauty against the backdrop of their rapidly industrializing world. Drawing on literary sources, poetry, and scenes from modern and medieval life, the Pre-Raphaelites established themselves as the most radical contemporary artists of the Victorian period by engaging in an aesthetic dialogue with art and artists from past centuries. Hunt, the oldest member of the group, believed he was the only one of the three founding PRB artists who remained true to the group’s mission throughout his career. This picture portrays a story from Giovanni Boccaccio’s Decameron (1353), adapted by the poet John Keats in 1818. Having exhumed her dead lover’s body, Isabella conceals his head inside a potted basil plant, watering it with tears. Hunt’s treatment was an exercise in mourning. He and his wife, Fanny Waugh, had traveled to Florence in 1866; she died there in December, and her memory served as his model for Isabella. Both the literary subject and various details of the composition (notably the majolica pot) demonstrate a Pre-Raphaelite fascination with early Italian art. A newly decorative sensibility, however, also signals the influence on Hunt’s work of the nascent Aesthetic Movement. He was so attached to this composition that he painted it twice. The prime version is in Newcastle.`,
		identifyingDescription: `The painting was previously on loan to the Fine Arts Museums for the Truth and Beauty exhibition in 2018. This is an artist-made replica made of a full-scale version in the Laing Art Gallery in Newcastle from 1867. It measures 74 x 46 in. (187 x 116 cm). A significant difference between the two paintings is the inlay pattern on the prie-dieu.`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		placeOfCreation: [`England`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 3313 — /artworks/porn-clip-8
	{
		id: `169191`,
		title: `Porn Clip #8`,
		artist: `Richard Bassett`,
		artistDates: `1948–2013`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-18891`,
				name: `Richard Bassett`,
				role: `Artist`,
				dates: `1948–2013`,
				nationality: `American`,
			},
		],
		date: `1999`,
		dateBegin: 1999,
		medium: `Graphite on paper`,
		dimensions: `524 x 476 mm (20 5/8 x 18 3/4 in.)`,
		creditLine: `Museum purchase, gift of David Ligare and Gary Smith in memory of Richard Bassett`,
		accession: `2013.46`,
		accessionDate: `2013`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Drawing`,
		onView: false,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 2740 — /artworks/horse-xx
	{
		id: `98377`,
		title: `Horse XX`,
		artist: `Nathan Oliveira`,
		artistDates: `1928–2010`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-8451`,
				name: `Nathan Oliveira`,
				role: `Artist`,
				dates: `1928–2010`,
				nationality: `American`,
			},
		],
		date: `1963`,
		dateBegin: 1963,
		medium: `Lithograph`,
		dimensions: `27.5 x 18 cm (image); 50.6 x 32.9 cm (sheet)`,
		creditLine: `Gift of the Artist`,
		accession: `1969.37.13`,
		accessionDate: `1969`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `abstract horse-like images (Annemarie Schutte 04/15/93)`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 2457 — /artworks/water-lilies
	{
		id: `97614`,
		title: `Water Lilies`,
		artist: `Claude Monet`,
		artistDates: `French, 1840–1926`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-6087`,
				name: `Claude Monet`,
				role: `Artist`,
				dates: `French, 1840–1926`,
				nationality: `French`,
			},
		],
		date: `ca. 1914–1917`,
		dateBegin: 1914,
		dateEnd: 1917,
		medium: `Oil on canvas`,
		dimensions: `Overall: 65 3/8 x 56 in. (166.1 x 142.2 cm) Framed: 78 1/2 x 64 7/8 in. (199.39 x 164.783 cm)`,
		creditLine: `Museum purchase, Mildred Anna Williams Collection`,
		accession: `1973.3`,
		accessionDate: `1973`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Dark blossoms and bright leaves drift among the reflected clouds on the water’s surface. No horizon is in sight. In the 1880s and 1890s, Monet developed a small natural pond on his property at Giverny into an extensive water garden inspired by Japanese ukiyo-e prints. This garden functioned as a kind of outdoor studio where he ultimately painted some two hundred fifty pictures, among them several of his most iconic works. This example likely dates to the mid-1910s but betrays no hint of the First World War raging not far from Giverny.`,
		placeOfCreation: [`Giverny`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 2393 — /artworks/porn-clip-7
	{
		id: `138292`,
		title: `Porn Clip #7`,
		artist: `Richard Bassett`,
		artistDates: `1948–2013`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-18891`,
				name: `Richard Bassett`,
				role: `Artist`,
				dates: `1948–2013`,
				nationality: `American`,
			},
		],
		date: `1999`,
		dateBegin: 1999,
		medium: `Graphite on paper`,
		dimensions: `Sheet: 524 x 476 mm (20 5/8 x 18 3/4 in.)`,
		creditLine: `Gift of Richard Bassett Estate, Donald Bradford, and Jack Fischer Gallery`,
		accession: `2013.39.1`,
		accessionDate: `2013`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Drawing`,
		onView: false,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 1684 — /artworks/aspiration
	{
		id: `65763`,
		title: `Aspiration`,
		artist: `Aaron Douglas`,
		artistDates: `1899–1979`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-4204`,
				name: `Aaron Douglas`,
				role: `Artist`,
				dates: `1899–1979`,
				nationality: `American`,
			},
		],
		date: `1936`,
		dateBegin: 1936,
		dateEnd: 1936,
		medium: `Oil on canvas`,
		dimensions: `60 x 60 in. (152.4 x 152.4 cm); Frame: 70 5/16 x 70 5/16 x 2 3/4 in. (178.6 x 178.6 x 7 cm)`,
		creditLine: `Museum purchase, the estate of Thurlow E. Tibbs Jr., the Museum Society Auxiliary, American Art Trust Fund, Unrestricted Art Trust Fund, partial gift of Dr. Ernest A. Bates, Sharon Bell, Jo-Ann Beverly, Barbara Carleton, Dr. And Mrs. Arthur H. Coleman, Dr. and Mrs. Coyness Ennix, Jr., Nicole Y. Ennix, Mr. and Mrs. Gary Francois, Dennis L. Franklin, Mr. and Mrs. Maxwell C. Gillette, Mr. and Mrs. Richard Goodyear, Zuretti L. Goosby, Marion E. Greene, Mrs. Vivian S. W. Hambrick, Laurie Gibbs Harris, Arlene Hollis, Louis A. and Letha Jeanpierre, Daniel and Jackie Johnson, Jr., Stephen L. Johnson, Mr. and Mrs. Arthur Lathan, Lewis & Ribbs Mortuary Garden Chapel, Mr. and Mrs. Gary Love, Glenn R. Nance, Mr. and Mrs. Harry S. Parker III, Mr. and Mrs. Carr T. Preston, Fannie Preston, Pamela R. Ransom, Dr. and Mrs. Benjamin F. Reed, San Francisco Black Chamber of Commerce, San Francisco Chapter of Links, Inc., San Francisco Chapter of the N.A.A.C.P., Sigma Pi Phi Fraternity, Dr. Ella Mae Simmons, Mr. Calvin R. Swinson, Joseph B. Williams, Mr. and Mrs. Alfred S. Wilsey, and the people of the San Francisco Bay Area`,
		accession: `1997.84`,
		accessionDate: `1997`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `"Aspiration," created for the Texas Centennial of 1936, conveys the artist’s perception of a link between African/Egyptian and African American cultures—rejecting European claims to Egypt’s historical legacy. Aaron Douglas’s painting depicts multiple progressions—from slavery to freedom, and from the agrarian or sharecropper labor of the South to the industrial labor of the North—along with the triumph of freedom over racism and subjugation. The shackled arms rising from wave-like curves evoke the transatlantic passage of slave ships. The five-pointed stars symbolize Texas—the Lone Star State—but also recall the North Star that guided fugitives from slavery to freedom before the Civil War. The seated figure of Egypt holding a book and the silhouettes of pyramids represent the cultural contributions of ancient African/Egyptian civilization. The two twentieth-century African American men hold attributes of education and gaze upward to a city whose futuristic skyscrapers symbolize human aspiration.`,
		placeOfCreation: [`United States`],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 1009 — /artworks/three-nude-french-girls-stand-out-in-a-grand-parade-from-le-chat-noir
	{
		id: `7078`,
		title: `Three Nude French girls stand out in a Grand Parade, from Le Chat Noir`,
		artist: `Adolphe Willette`,
		artistDates: `1857–1926`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-3112`,
				name: `Adolphe Willette`,
				role: `Artist`,
				dates: `1857–1926`,
				nationality: `French`,
			},
		],
		date: `19th–20th century`,
		medium: `Gillotage`,
		dimensions: ``,
		creditLine: `Achenbach Foundation for Graphic Arts`,
		accession: `1963.30.19773`,
		accessionDate: `1963`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 854 — /artworks/eiffel-tower
	{
		id: `92641`,
		title: `Eiffel Tower`,
		artist: `Georges Seurat`,
		artistDates: `1859–1891`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-13460`,
				name: `Georges Seurat`,
				role: `Artist`,
				dates: `1859–1891`,
				nationality: `French`,
			},
		],
		date: `ca. 1889`,
		dateBegin: 1884,
		dateEnd: 1894,
		medium: `Oil on wood panel`,
		dimensions: `9 7/8 x 6 3/16 in. (25.083 x 15.716 cm)`,
		creditLine: `Museum purchase, William H. Noble Bequest Fund`,
		accession: `1979.48`,
		accessionDate: `1979`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `The inventor of the so-called Neo-Impressionist, or pointillist, technique, Seurat used tiny dots of bright, contrasting color to evoke form and light. His technique drew on contemporary theories of visual perception, seeking to give painting a new structure and scientific grounding. Here his subject was the famous tower built by Gustave Eiffel in 1889 for the Universal Exposition in Paris. Seurat portrayed the structure prior to its completion in the summer of 1889. The top, still missing its distinctive crowning platform, seems to dissolve into the sky.`,
		placeOfCreation: [`Paris`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 780 — /artworks/untitled-11851
	{
		id: `147493`,
		title: `Untitled 1 and 2, WP1-3`,
		artist: `Brad Brown`,
		artistDates: `b. 1964`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-12613`,
				name: `Brad Brown`,
				role: `Artist`,
				dates: `b. 1964`,
				nationality: `American`,
			},
		],
		date: `1999`,
		dateBegin: 1999,
		medium: ``,
		dimensions: `Sheet: 567 x 752 mm (22 5/16 x 29 5/8 in.)`,
		creditLine: `Crown Point Press Archive, gift of Crown Point Press`,
		accession: `2020.36.41`,
		accessionDate: `2020`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `color proof of large plates before cut to make Untitled 1 and Untitled 2`,
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 758 — /artworks/petunias
	{
		id: `63250`,
		title: `Petunias`,
		artist: `Georgia O'Keeffe`,
		artistDates: `American, 1887–1986`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-8431`,
				name: `Georgia O'Keeffe`,
				role: `Artist`,
				dates: `American, 1887–1986`,
				nationality: `American`,
			},
		],
		date: `1925`,
		dateBegin: 1925,
		dateEnd: 1925,
		medium: `Oil on hardboard`,
		dimensions: `18 x 30 in. (45.7 x 76.2 cm)`,
		creditLine: `Museum purchase, gift of the M. H. de Young Family`,
		accession: `1990.55`,
		accessionDate: `1990`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Georgia O’Keeffe employed modernist artistic strategies to inspire wonder in the natural world. She is perhaps best known for her flower paintings, which challenged traditional associations with still-life painting. Instead, O’Keeffe’s monumental blossoms suggest personal narratives, elaborate metaphors, and radical self-expression: “I found I could say things with color and shapes that I couldn’t say any other way . . . things I had no words for.” "Petunias" was inspired by a patch of purple petunias that O’Keeffe planted at the Stieglitz family summer home near Lake George in upstate New York the year that she and Alfred Stieglitz were married. She began painting the flowers in the summer of 1925, and this is one of a dozen works of various sizes and perspectives that she painted from those plants over the next two years. This work is the most complex in the series: featuring six blossoms posed at different angles and at various stages of blooming, it almost seems like a dynamic portrait of a single flower moving through space and time. O’Keeffe animated each petal with velvety textures and crisp contours, and the immense scale of each blossom confronts the divide between representation and abstraction. The flowers fill the composition, touching every edge of the picture. This cropping effect, and the composition’s resemblance to a close-up image, might be attributed to the influence of modern photographic techniques. Petunias may also signal the influence of Luther Burbank’s dramatically illustrated seed catalogues, which O’Keeffe consulted while selecting plants for the orchards and gardens around the Stieglitz property. [Lauren Palmor, de Young 125]`,
		identifyingDescription: `six (?) purple flowers, two showing green stamens; gray,white,blue background`,
		placeOfCreation: [`United States`],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 725 — /artworks/three-machines
	{
		id: `84904`,
		title: `Three Machines`,
		artist: `Wayne Thiebaud`,
		artistDates: `American, 1920–2021`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-14902`,
				name: `Wayne Thiebaud`,
				role: `Artist`,
				dates: `American, 1920–2021`,
				nationality: `American`,
			},
		],
		date: `1963`,
		dateBegin: 1963,
		dateEnd: 1963,
		medium: `Oil on canvas`,
		dimensions: `Overall: 30 x 36 1/2 in. (76.2 x 92.71 cm)`,
		creditLine: `Museum purchase, Walter H. and Phyllis J. Shorenstein Foundation Fund, the Roscoe and Margaret Oakes Income Fund, with additional funds from Claire E. Flagg, the Museum Society Auxiliary, Mr. and Mrs. George R. Roberts, Mr. and Mrs. John N. Rosekrans, Jr., Mr. and Mrs. Robert Bransten, Mr. and Mrs. Steven MacGregor Read, and Bobbie and Mike Wilsey, from the Morgan Flagg Collection`,
		accession: `1993.18`,
		accessionDate: `1993`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: false,
		labelText: `Wayne Thiebaud’s lushly painted representations of American bakery, delicatessen, and restaurant food displays challenge our preconceptions about what we should consider worthy subjects for fine art, and reveal the fluid boundaries between representation and abstraction. The ostensible realism of "Three Machines" obscures its artifice. As Thiebaud observed, “Realism . . . seemed alternately the most magical alchemy on the one hand, and on the other the most abstract construct intellectually.” Thiebaud’s nearly anthropological renderings of American popular culture reveal larger truths. Gumballs are the common denominator of penny candy—a sort of atomic particle of American consumer culture. They also represent, in microcosm, a common cycle of American consumerism, which spans from an imagined ideal, to the pleasure of possession, to a state of diminishing returns, and finally to a sense of loss—until the cycle begins again.`,
		placeOfCreation: [`California`],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 660 — /artworks/woman-bathing-la-toilette
	{
		id: `105697`,
		title: `Woman Bathing (La Toilette)`,
		artist: `Mary Cassatt`,
		artistDates: `American, active France, 1844–1926`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-7175`,
				name: `Mary Cassatt`,
				role: `Artist`,
				dates: `American, active France, 1844–1926`,
				nationality: `American`,
			},
		],
		date: `1890–1891`,
		dateBegin: 1890,
		dateEnd: 1891,
		medium: `Color aquatint, softground etching, and drypoint on paper`,
		dimensions: `18 3/4 x 12 1/4 in. (47.625 x 31.115 cm) Plate Mark: 14 3/8 x 10 1/2 in. (36.5 x 26.6 cm) Frame: 28 3/4 x 23 7/8 x 1 in. (73.025 x 60.643 x 2.54 cm)`,
		creditLine: `Museum purchase, Achenbach Foundation for Graphic Arts Endowment Fund and William H. Noble Bequest Fund`,
		accession: `1980.1.8`,
		accessionDate: `1980`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		labelText: `ln 1890, Cassatt saw an impressive exhibition of more than seven hundred Japanese prints at the École des Beaux-Arts. Though she was already fascinated by Japanes art and culture, the exhibition compelled her to recognize the prints' value in her own art. Almost immediately, Cassatt embarked on an ambitious project of color aquatints based on ukiyo-e models. Working intensely over several months in 1890 and 1891, Cassatt completed a set of ten color aquatints, including Woman Bathing. The print contains a number of Japanese-inspired devices, among them unusual viewpoints, flat areas of color, strong diagonals, flattening of forms, and emphasis on pattern and line. Though it is not clear that the subject of a woman shown going about an everyday activity is borrowed from the Japanese prints of courtesans and beauties, there is no doubt that Cassatt's palette was determined by those prints. The dusty blue, pink, umber, and green tones are identical to the subdued color schemes in the eighteenth-century prints of Kitagawa Utamaro, one of Cassatt's favored influences.`,
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 645 — /artworks/el-aborto-frida-and-the-miscarriage
	{
		id: `69417`,
		title: `El Aborto (Frida and the Miscarriage)`,
		artist: `Frida Kahlo`,
		artistDates: `Mexican, 1907–1954`,
		artistNationality: ``,
		constituents: [
			{
				id: `C-18103`,
				name: `Frida Kahlo`,
				role: `Artist`,
				dates: `Mexican, 1907–1954`,
			},
		],
		date: `1932`,
		dateBegin: 1932,
		dateEnd: 1932,
		medium: `Lithograph`,
		dimensions: `Image: 8 3/4 x 5 9/16 in. (22.2 x 14.2 cm)`,
		creditLine: `Museum purchase, Dr. R. Earl Robinson Estate and Achenbach Foundation for Graphic Arts Endowment Fund`,
		accession: `1996.38`,
		accessionDate: `1996`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		labelText: `In the late 1920's, Kahlo joined the Mexican Communist Party and was introduced to a circle of political activists and artists, among them Diego Rivera, whom she married in 1929. She traveled extensively in the United States with Rivera beginning in 1930 as he undertook mural projects in San Francisco and opened his retrospective at the Museum of Modern Art in New York. While he was working on a mural project in Detroit, Kahlo experienced a miscarriage following a difficult pregnancy. In 1925, while she was pursuing medical school, Kahlo had experienced a crippling traffic accident that would cause her lifelong pain and ultimately made it impossible for her to bear children. To combat her depression during her recovery from the miscarriage, Kahlo was convinced to try lithography at a local printmaking workshop, where she struggled with the medium. One of only six known impressions from this experience, El Aborto is the only significant print she ever made. It is graphic in its anatomical references to her miscarriage, but powerful in its symbolism. Biographer Hayden Herrera observed that in the print Kahlo's body is divided into light and dark halves, revealing the two sides of her psyche; it would seem that for her, making art must take the place of making children. Karin Breuer`,
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 582 — /artworks/the-russian-brides-attire
	{
		id: `209712`,
		title: `The Russian Bride's Attire`,
		artist: `Konstantin Makovsky`,
		artistDates: `1839–1915`,
		artistNationality: `Russian`,
		constituents: [
			{
				id: `C-17226`,
				name: `Konstantin Makovsky`,
				role: `Artist`,
				dates: `1839–1915`,
				nationality: `Russian`,
			},
		],
		date: `1889`,
		dateBegin: 1889,
		medium: `Oil on canvas`,
		dimensions: `110 x 147 in. (279.4 x 373.4 cm)`,
		creditLine: `Bequest of M.H. de Young`,
		accession: `53161`,
		accessionDate: `1926`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		placeOfCreation: [`Russia`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 576 — /artworks/naked-x
	{
		id: `146302`,
		title: `Naked X`,
		artist: `Richard Tuttle`,
		artistDates: `b. 1941`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-16070`,
				name: `Richard Tuttle`,
				role: `Artist`,
				dates: `b. 1941`,
				nationality: `American`,
			},
			{
				id: `C-14350`,
				name: `Rachel Fuller`,
				role: `Printer`,
			},
			{
				id: `C-7900`,
				name: `Crown Point Press`,
				role: `Printer`,
				dates: `est. 1962`,
			},
		],
		date: `2004`,
		dateBegin: 2004,
		medium: `color soft-ground etching with drypoint and hand-staining on senka-shi paper`,
		dimensions: `Sheet: 635 x 508 mm (25 x 20 in.)`,
		creditLine: `Crown Point Press Archive, Gift of Crown Point Press`,
		accession: `2006.44.19.10`,
		accessionDate: `2006`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `AP 6. Edition 10`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 555 — /artworks/white-sex
	{
		id: `164167`,
		title: `White Sex`,
		artist: `Peter Saul`,
		artistDates: `b. 1934`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-279`,
				name: `Peter Saul`,
				role: `Artist`,
				dates: `b. 1934`,
				nationality: `American`,
			},
		],
		date: `1966`,
		dateBegin: 1966,
		medium: `lithograph`,
		dimensions: `: 322 x 480 mm (12 11/16 x 18 7/8 in.)`,
		creditLine: `Gift of Roland C. Petersen`,
		accession: `2001.137.16`,
		accessionDate: `2001`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `1/10 black and white`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 547 — /artworks/the-ironworkers-noontime
	{
		id: `107071`,
		title: `The Ironworkers' Noontime`,
		artist: `Thomas Pollock Anshutz`,
		artistDates: `American, 1851–1912`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-2295`,
				name: `Thomas Pollock Anshutz`,
				role: `Artist`,
				dates: `American, 1851–1912`,
				nationality: `American`,
			},
		],
		date: `1880`,
		dateBegin: 1880,
		dateEnd: 1880,
		medium: `Oil on canvas`,
		dimensions: `Overall: 17 1/8 x 24 1/8 in. (43.498 x 61.278 cm) Framed: 23 x 29 7/8 in. (58.42 x 75.883 cm)`,
		creditLine: `Gift of Mr. and Mrs. John D. Rockefeller 3rd`,
		accession: `1979.7.4`,
		accessionDate: `1979`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Born in Kentucky, Thomas Pollock Anshutz moved with his family in 1863 to Wheeling, West Virginia, where he spent his teenage years growing up amid the region's urban factories that dominated the banks of the Ohio River. He went on to becomes one of the most important art teachers in the United States, teaching for nearly three decades at the Pennsylvania Academy of the Fine Arts (PAFA) in Philadelphia, where he influenced the next generation of American realist painters. The Ironworkers' Noontime portrays a group of workers at a nail factory in Wheeling, West Virginia. The workers are displayed across a shallow foreground, while the colossal foundry stretches as far as the eye can see. Anshutz began the preparatory drawings for this picture during one of his yearly visits to see family who lived in Wheeling. The labor he depicts was then being impacted by increasing mechanization, which posed a threat to skilled American workers.`,
		signed: `Signed lower left: Thos. Anshutz`,
		placeOfCreation: [`United States`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 547 — /artworks/russian-nude
	{
		id: `166254`,
		title: `Russian Nude`,
		artist: `Daniel J. Robeski`,
		artistDates: `1951–2002`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-13880`,
				name: `Daniel J. Robeski`,
				role: `Artist`,
				dates: `1951–2002`,
				nationality: `American`,
			},
		],
		date: `1994`,
		dateBegin: 1994,
		medium: `woodcut`,
		dimensions: `Sheet: 526 x 430 mm (20 11/16 x 16 15/16 in.)`,
		creditLine: `Gift of the Family of the Artist`,
		accession: `2003.39.2`,
		accessionDate: `2003`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `1/10`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 532 — /artworks/the-thinker
	{
		id: `34427`,
		title: `The Thinker`,
		artist: `Auguste Rodin`,
		artistDates: `French, 1840 - 1917`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-10610`,
				name: `Auguste Rodin`,
				role: `Artist`,
				dates: `French, 1840 - 1917`,
				nationality: `French`,
			},
			{
				id: `C-18416`,
				name: `Alexis Rudier`,
				role: `Maker`,
				dates: `French, 1854 - 1897`,
				nationality: `French`,
			},
			{
				id: `C-40818`,
				name: `Rudier Foundry`,
				role: `Foundry`,
				dates: `1874 - 1952`,
			},
		],
		date: `1904`,
		dateBegin: 1904,
		medium: `Cast bronze`,
		dimensions: `72 x 38 x 54 (182.9 x 96.5 x 137.2 cm)`,
		creditLine: `Gift of Alma de Bretteville Spreckels`,
		accession: `1924.18.1`,
		accessionDate: `1925`,
		department: `European Decorative Arts and Sculpture`,
		classification: `Sculpture`,
		onView: true,
		labelText: `Rodin's The Thinker is perhaps his best-known monumental work. First conceived about 1880 as the poet Dante, it was designed to occupy the center of the tympanum of The Gates of Hell, an unrealized scheme for a portal. In subsequent years, the figure evolved into a broader physical representation of the creative process. The Thinker was first exhibited in Paris at the Exposition Monet-Rodin in 1889 and an enlarged version was shown at the Paris Salon of 1904. Displayed at the 1915 Panama-Pacific International Exposition in San Francisco, this cast was purchased from the artist by Adolph andAlma Spreckels. It was one of the first of more than ninetyRodin sculptures Mrs. Spreckels later donated to the Legion of Honor.`,
		inscriptions: `(base, front, upper center, inscribed in bronze) Rodin (base, rear, lower right, in bronze) A. Rudier. Fondeur. Paris`,
		identifyingDescription: `Inscribed at top front of base: “Rodin”; Foundry Mark rear lower right side of Base: “A. Rudier. Fondeur. Paris”.`,
		placeOfCreation: [`France`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 494 — /artworks/the-bath
	{
		id: `104457`,
		title: `The Bath`,
		artist: `Jean-Léon Gérôme`,
		artistDates: `1824–1904`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-14438`,
				name: `Jean-Léon Gérôme`,
				role: `Artist`,
				dates: `1824–1904`,
				nationality: `French`,
			},
		],
		date: `ca. 1880–1885`,
		dateBegin: 1875,
		dateEnd: 1890,
		medium: `Oil on canvas`,
		dimensions: `29 x 23 1/2 in. (73.7 x 59.7 cm)`,
		creditLine: `Museum purchase, Mildred Anna Williams Collection`,
		accession: `1961.29`,
		accessionDate: `1961`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Though the French artist Jean-Léon Gérôme made multiple voyages to North Africa and the Eastern Mediterranean—and painted many pictures inspired by his travels—his work draws at least as much from fantasy and stereotype as from observation. Superb technical skills allowed him to conjure the scenes he painted with a seductive realism, here evident in the treatment of wet tile, rumpled cloth, and bare skin. Relying on sketches, photographs, and props brought back from various corners of the Ottoman Empire, Gérôme painted such scenes in the comfort of his Paris studio, hiring local models to act out the roles of women in an imaginary harem. In reality, as a man and an outsider, Gérôme could never have entered a space like the one depicted here. The harem was a private area reserved for women, children, and domestic workers (whether paid or enslaved) in wealthy Ottoman households. In the nineteenth-century European imagination, however, harems formed an object of prurient curiosity and the locus of imagined Eastern otherness, defined by luxury, sensuality, and cruelty. While both figures depicted here could be free or enslaved members of a harem Gérôme's composition imposes a racialized social hierarchy (white bather vs. Black attendant) characteristic of European thinking in the period. Of course the real-life women playing both roles were likely professional models from Northern Paris, home in the later nineteenth century to significant working-class and French-Caribbean populations. Deeply informed by racist ideology and the French colonial enterprise, Gérôme's harem paintings belong to a genre known as Orientalism. -Emily A. Beeny`,
		placeOfCreation: [`France`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 473 — /artworks/rainy-season-in-the-tropics
	{
		id: `96340`,
		title: `Rainy Season in the Tropics`,
		artist: `Frederic Edwin Church`,
		artistDates: `1826–1900`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-6402`,
				name: `Frederic Edwin Church`,
				role: `Artist`,
				dates: `1826–1900`,
				nationality: `American`,
			},
		],
		date: `1866`,
		dateBegin: 1866,
		dateEnd: 1866,
		medium: `Oil on canvas`,
		dimensions: `56 1/4 x 84 1/4 in. (142.9 x 214 cm); Frame: 77 1/2 x 107 x 6 in. (196.9 x 271.8 x 15.3 cm)`,
		creditLine: `Museum purchase, Mildred Anna Williams Collection`,
		accession: `1970.9`,
		accessionDate: `1970`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Critic Henry Tuckerman praised this imaginary landscape, inspired by Frederic E. Church's extensive travels: "Athwart a mountain-bounded valley and gorge . . . the sunshine, beaming across the vapory vail, forms thereon a rainbow, which seems to clasp the whole with a prismatic bridge; a scene more characteristic of the season and the region it is difficult to imagine, and one more difficult to represent on canvas could not be selected. To combine the right perspective with the aqueous effects is a problem hard to solve; but Mr. Church has succeeded; the aerial perspective is exquisitely true—the floating vapor, the blue sky, the radiant iris—the brooding mists on the distant mountains, the rich vegetation of the foreground, and green, rugged, declivity and mule-path—water, air, cloud, hill, and vale—all wear the tearful glory of The Rainy Season in the Tropics." [Henry Tuckerman, “Church,” in Book of the Artists, American Artist Life (New York: G. P. Putnam & Son, 1867) Audio tour stops 325, 24.]`,
		placeOfCreation: [`United States`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 442 — /artworks/susanna-and-the-elders
	{
		id: `149961`,
		title: `Susanna and the Elders`,
		artist: `Hendrick Goltzius`,
		artistDates: `1565–1607`,
		artistNationality: `Dutch`,
		constituents: [
			{
				id: `C-14518`,
				name: `Hendrick Goltzius`,
				role: `After`,
				dates: `1558–1617`,
				nationality: `Dutch`,
			},
			{
				id: `C-13305`,
				name: `Jan Saenredam`,
				role: `Artist`,
				dates: `1565–1607`,
				nationality: `Dutch`,
			},
		],
		date: `ca. late 16th century`,
		medium: `engraving`,
		dimensions: `Plate: 250 x 170 mm (9 13/16 x 6 11/16 in.)`,
		creditLine: `Mr. and Mrs. Marcus Sopher Collection`,
		accession: `2000.156.33`,
		accessionDate: `2000`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `A young, partially clothed seated Susanna with two women looking on right next to her.`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 422 — /artworks/roman-fish-market-arch-of-octavius
	{
		id: `94409`,
		title: `Roman Fish Market. Arch of Octavius`,
		artist: `Albert Bierstadt`,
		artistDates: `American, born Germany, 1830–1902`,
		artistNationality: `American, b. Germany`,
		constituents: [
			{
				id: `C-7647`,
				name: `Albert Bierstadt`,
				role: `Artist`,
				dates: `American, born Germany, 1830–1902`,
				nationality: `American, b. Germany`,
			},
		],
		date: `1858`,
		dateBegin: 1858,
		dateEnd: 1858,
		medium: `Oil on canvas`,
		dimensions: `27 5/8 x 37 3/8 in. (70.2 x 94.9 cm)`,
		creditLine: `Gift of Mr. and Mrs. John D. Rockefeller 3rd`,
		accession: `1979.7.12`,
		accessionDate: `1979`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Ancient Rome’s Portico of Octavia, built by Emperor Augustus in 23 BC, gradually fell into ruin and became a fish market in the twelfth century. When Albert Bierstadt traveled to Italy in 1857, Rome was defined largely by its historical roles in the Roman Empire and the Italian Renaissance. It was also the most important destination for wealthy tourists who made the Grand Tour of Europe to view the roots of Western civilization. Americans like the man clutching his Rome guidebook and his wary wife considered themselves the heirs of ancient Greek and Roman ideals, emulating their democracies and architecture. Yet Bierstadt’s painting documents the decline and fall of ancient Rome’s monuments, while two famous antique statues, the Sleeping Endymion and the Barberini Faun, are reincarnated in a sleeping man and a street sweeper. The fish-scale and scallop-shell frame motifs offer a playful pun on Bierstadt’s subject.`,
		signed: `Signed & dated lower right: ABierstadt/1858`,
		placeOfCreation: [`New York`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 391 — /artworks/little-nude-from-seven-objects-in-a-box
	{
		id: `116990`,
		title: `Little Nude from Seven Objects in a Box`,
		artist: `Tom Wesselmann`,
		artistDates: `1931–2004`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-3076`,
				name: `Tom Wesselmann`,
				role: `Artist`,
				dates: `1931–2004`,
				nationality: `American`,
			},
			{
				id: `C-15467`,
				name: `Knickerbocker Machine and Foundry, Inc. (KMF)`,
				role: `Manufacturer`,
				dates: `active 20th century`,
				nationality: `American`,
			},
			{
				id: `C-13953`,
				name: `Tanglewood Press, Inc.`,
				role: `Publisher`,
				dates: `American, active 20th century`,
			},
		],
		date: `1966`,
		dateBegin: 1966,
		medium: `Color stencil printed on vacuum-formed plexiglas backed with foam`,
		dimensions: `7 5/16 x 7 11/16 x 1 in. (18.5 x 19.5 x 2.5 cm)`,
		creditLine: `Gift of Allan P. and Lenore B. Sindler`,
		accession: `1988.1.199.7`,
		accessionDate: `1988`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 390 — /artworks/portrait-of-orleans
	{
		id: `53349`,
		title: `Portrait of Orleans`,
		artist: `Edward Hopper`,
		artistDates: `1882–1967`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-15911`,
				name: `Edward Hopper`,
				role: `Artist`,
				dates: `1882–1967`,
				nationality: `American`,
			},
		],
		date: `1950`,
		dateBegin: 1950,
		dateEnd: 1950,
		medium: `Oil on canvas`,
		dimensions: `26 x 40 in. (66 x 101.6 cm)`,
		creditLine: `Gift of Jerrold and June Kingsley`,
		accession: `1991.32`,
		accessionDate: `1991`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Edward Hopper’s symbolic portrait of Orleans, a town on Cape Cod in Massachusetts, documents the dramatic transformation of the American landscape after World War II. The vantage point is that of a car driver who will either continue straight onto Main Street or will turn right onto Route 6A. In this nostalgic view of Main Street America, the stilled pedestrian, car, and clock all seem to suggest that time has stopped. However, the modern Esso gas station sign in the foreground documents the post–World War II growth of corporate culture in general and car culture in particular. The prominent telephone pole lacks wires and thus functions more like a symbolic cross on a religious pilgrimage route. The gas station enabled motorists to continue on their journey to the resort towns of Cape Cod, where Hopper had built a house in 1934, while the small-town way of life epitomized by Orleans rapidly receded into the distance.`,
		placeOfCreation: [`Orleans`],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 384 — /artworks/third-class-carriage
	{
		id: `91905`,
		title: `Third-Class Carriage`,
		artist: `Honoré Daumier`,
		artistDates: `1808–1879`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-9878`,
				name: `Honoré Daumier`,
				role: `Artist`,
				dates: `1808–1879`,
				nationality: `French`,
			},
		],
		date: `ca. 1856–1858`,
		dateBegin: 1851,
		dateEnd: 1863,
		medium: `Oil on wood panel`,
		dimensions: `10 1/4 x 13 3/8 in. (26 x 33.9 cm)`,
		creditLine: `Museum purchase, Whitney Warren, Jr. Bequest Fund in memory of Mrs. Adolph B. Spreckels, Bequest funds of Henry S. Williams in memory of H.K.S. Williams, Magnin Income Fund, Art Trust Fund, Alexander and Jean de Bretteville Fund, Art Acquisition Endowment Income Fund in honor of Mrs. John N. Rosekrans`,
		accession: `1996.51`,
		accessionDate: `1996`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Third-Class Carriage is one of many pictures Daumier painted of passengers on trains, a novel form of transport in the nineteenth century. The growth of France's railway network under the Second Empire (1852-1870) made travel swifter and more accessible, but the journey was not the same for everyone. Railway companies separated passengers into three classes through a tiered ticketing system that corresponded to the level of comfort onboard. Here Daumier depicted travelers who have paid the lowest fare: a peasant mother and child, an old woman, and a worker in a rumpled smock. Crowded together with other passengers in a dark compartment, these careworn figures exemplify Daumier’s unapologetic Realism.`,
		placeOfCreation: [`France`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 366 — /artworks/still-life-with-skull-leeks-and-pitcher-march-14-1945
	{
		id: `109433`,
		title: `Still Life with Skull, Leeks, and Pitcher, March 14, 1945`,
		artist: `Pablo Picasso`,
		artistDates: `Spanish, 1881–1973`,
		artistNationality: ``,
		constituents: [
			{
				id: `C-8623`,
				name: `Pablo Picasso`,
				role: `Artist`,
				dates: `Spanish, 1881–1973`,
			},
		],
		date: `1945`,
		dateBegin: 1945,
		dateEnd: 1945,
		medium: `Oil on canvas`,
		dimensions: `28 3/4 x 45 5/8 in. (73 x 115.9 cm)`,
		creditLine: `Museum purchase, Whitney Warren Jr. Bequest Fund in memory of Mrs. Adolph B. Spreckels, Grover A. Magnin Bequest Fund, Roscoe and Margaret Oakes Income Fund and Bequest of Mr. and Mrs. Frederick J. Hellman, by exchange`,
		accession: `1992.1`,
		accessionDate: `1992`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Still Life with Skull, Leeks, and Pitcher belongs to a lengthy series of still life paintings that Picasso produced on the themes of war, death, and suffering during the years of World War II, when he was living in Paris under German Occupation. Most commonly, Picasso’s paintings of this period feature a grim expressiveness emanating from a dark and lifeless palette of black and grays, stark and even monstrous distortions of form, and closed-off, claustrophobic pictorial spaces. The distressing tenor of such work was set by his famous antiwar mural Guernica, painted in 1937 during the Spanish Civil War. In this particular painting, the color scheme and overall mood is brighter, despite the presence of the grimacing skull, a reminder of death relating to the long tradition of memento mori and vanitas themes in Western art. The leeks, as Picasso reported in conversation, substitute for crossed bones but also add a note of organic vitality that contrasts with the cold white form of the death’s-head. The pitcher, which may symbolize a human figure standing and contemplating the skull, is bold in scale and patterning as well as in its use of the red, white, and blue colors of the French flag. The sharp angulations of the table and background are painted in mostly pastel hues and include a ray of golden sunlight that reflects off the wall and down across the black shadow on the side of the skull. All in all, the lighter, more optimistic feeling of this work must reflect, in March 1945, Picasso’s anticipation of a rapid conclusion to the war. -Steve A. Nash, Masterworks of European Painting in the California Palace of the Legion of Honor (1999)`,
		identifyingDescription: `abstract painting with the above on table,dated upper left corner "14 3 45 "signed lower right corner "Picasso"`,
		placeOfCreation: [`Spain`],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 359 — /artworks/the-grand-canal-venice
	{
		id: `18700`,
		title: `The Grand Canal, Venice`,
		artist: `Hanx Ludwig Ernest Kaumann`,
		artistDates: `b. 1886`,
		artistNationality: `German`,
		constituents: [
			{
				id: `C-801`,
				name: `Hanx Ludwig Ernest Kaumann`,
				role: `Artist`,
				dates: `b. 1886`,
				nationality: `German`,
			},
		],
		date: `1924`,
		dateBegin: 1924,
		medium: `Etching (on Japan paper)`,
		dimensions: `19.7 x 24.8 cm (image)`,
		creditLine: `Achenbach Foundation for Graphic Arts`,
		accession: `1963.30.34531`,
		accessionDate: `1963`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `Typical view of the grand canal and Venetian buildings and gondolas.`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 343 — /artworks/the-broken-pitcher
	{
		id: `258886`,
		title: `The Broken Pitcher`,
		artist: `William-Adolphe Bouguereau`,
		artistDates: `1825–1905`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-4446`,
				name: `William-Adolphe Bouguereau`,
				role: `Artist`,
				dates: `1825–1905`,
				nationality: `French`,
			},
		],
		date: `1891`,
		dateBegin: 1891,
		medium: `Oil on canvas`,
		dimensions: `53 x 33 in. (134.6 x 83.8 cm)`,
		creditLine: `Bequest of M.H. de Young`,
		accession: `53162`,
		accessionDate: `1926`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `William-Adolphe Bouguereau was one of the most famous and influential French academic artists of the later nineteenth century. His Broken Pitcher of 1891 exhibits many of the stylistic qualities central to academic teaching of the time, including the careful description of forms with clear contours and smooth three-dimensional modeling, an idealized approach to the human figure, and balanced, architectural massing within the composition. It also manifests the penchant for infusing sentimentality and even light eroticism into the most time-honored subjects. In theme, The Broken Pitcher draws on a fashion for peasant or rural imagery pioneered by Gustave Courbet and Jean-François Millet around mid-century. Bouguereau produced from the 1860s onward a long series of one-or-two figure compositions that were often sexually allusive, featuring French and Italian country girls. Here, the cracked pitcher stands for the loss of virginity, the spout of the well provides a counterbalancing male symbol, and the girl’s plaintive expression erases any doubts about the picture’s true meaning, calculated to appeal to the prurient interests of a male-dominated upper-middle class French art market. Nevertheless, Bouguereau’s flawless technique and play upon the heart have always given the painting broad public appeal. This work is recorded as having entered the collection of Mr. and Mrs. M.H. de Young in San Francisco by May 1893 and is very likely the first painting by Bouguereau to reach California. -Steve A. Nash, Masterworks of European Painting in the California Palace of the Legion of Honor (1999)`,
		placeOfCreation: [`France`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 324 — /artworks/the-holy-family-with-the-infant-saint-john-the-baptist
	{
		id: `100168`,
		title: `The Holy Family with the Infant Saint John the Baptist`,
		artist: `Simon Vouet`,
		artistDates: `1590–1649`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-2988`,
				name: `Simon Vouet`,
				role: `Artist`,
				dates: `1590–1649`,
				nationality: `French`,
			},
		],
		date: `1626`,
		dateBegin: 1626,
		dateEnd: 1626,
		medium: `Oil on wood panel later transferred to hardboard`,
		dimensions: `Overall: 29 7/16 x 29 1/2 in. (74.771 x 74.93 cm) Framed: 38 1/2 x 38 1/2 x 4 in. (97.79 x 97.79 x 10.16 cm)`,
		creditLine: `Museum purchase, Mildred Anna Williams Collection`,
		accession: `1974.8`,
		accessionDate: `1974`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Simon Vouet's career was forged in Rome, where he arrived by 1614 with a pension from the French crown. He made the most of this rich experience, absorbing the lessons of Caravaggio, the Northern artists resident there and contemporary Roman painters, all of whom were articulating the baroque style. Recognized first as a portraitist, Vouet gradually acquired a circle of influential patrons who provided commissions to decorate palaces and churches in classical grandeur. The second phase of his career began in 1627 when Louis XIII recalled Vouet to Paris. In France Vouet evolved a new pictorial language, lightening his palette, creating glorious color harmonies, and filling his rhythmic compositions with beautiful, sensuous figures. Established as the leading painter of his generation, he maintained a large teaching studio that shaped the oeuvre of many younger artists. This important painting is believed to have been executed in Rome in 1626, shortly before it entered the Barberini collection and before Vouet returned to Paris. Although the subject had been treated often, Vouet renewed its timeless appeal with sensitive coloring, shimmering effects of light on the tree branches and the children's hair, and the happy, pensive expression of the Virgin Mary. The pyramidal structure and quiet charm of this devotional image reflect the initial influences of Vouet's Italian sojourn.`,
		signed: `(front, lower right on column, in brown paint) SIMON VOV[ET]/ ROMA 16[illegible]`,
		inscriptions: `(back, left, in black ink) 24452; (back, left, in black marker) FAM-SF/#1974.8; (back, right, in black marker) VOUET`,
		placeOfCreation: [`France`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 321 — /artworks/the-tribute-money
	{
		id: `112645`,
		title: `The Tribute Money`,
		artist: `Peter Paul Rubens`,
		artistDates: `1577–1640`,
		artistNationality: `Flemish`,
		constituents: [
			{
				id: `C-10682`,
				name: `Peter Paul Rubens`,
				role: `After`,
				dates: `1577–1640`,
				nationality: `Flemish`,
			},
			{
				id: `C-2985`,
				name: `Lucas Vorsterman the Elder`,
				role: `After`,
				dates: `circa 1595–1675`,
				nationality: `Flemish`,
			},
			{
				id: `C-7817`,
				name: `Claes Jansz Visscher the Elder`,
				role: `Publisher`,
				dates: `1586–1652`,
				nationality: `Dutch`,
			},
		],
		date: `after 1621`,
		dateBegin: 1621,
		medium: `Engraving`,
		dimensions: `Image: 402 x 503 mm (15 13/16 x 19 13/16 in.) trimmed; Sheet: 402 x 503 mm (15 13/16 x 19 13/16 in.) trimmed`,
		creditLine: `Mr. and Mrs. Marcus Sopher Collection`,
		accession: `1993.63.65`,
		accessionDate: `1993`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `inside a classical building, Christ surrounded by men, holds a coin`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 302 — /artworks/zwei-spielende-nackte-madchen-two-nude-girls-playing
	{
		id: `10726`,
		title: `Zwei spielende nackte Mädchen (Two Nude Girls Playing)`,
		artist: `Ernst Ludwig Kirchner`,
		artistDates: `German, 1880–1938`,
		artistNationality: `German`,
		constituents: [
			{
				id: `C-840`,
				name: `Ernst Ludwig Kirchner`,
				role: `Artist`,
				dates: `German, 1880–1938`,
				nationality: `German`,
			},
		],
		date: `1923`,
		dateBegin: 1923,
		medium: `Woodcut on yellow paper`,
		dimensions: `Image: 675 x 378 mm (26 9/16 x 14 7/8 in.); Sheet: 780 x 460 mm (30 11/16 x 18 1/8 in.) irregular`,
		creditLine: `Museum purchase, Funds from the Patrons of Art and Music`,
		accession: `1960.72.25`,
		accessionDate: `1960`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		identifyingDescription: `taller and shorter nude females in outdoor setting (grass and trees)`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 300 — /artworks/portrait-of-bianca-degli-utili-maselli-and-her-children
	{
		id: `67192`,
		title: `Marie Antoinette and her Two Children (?)`,
		artist: `Pierre Alexandre Wille`,
		artistDates: `1748–1837`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-3110`,
				name: `Pierre Alexandre Wille`,
				role: `Artist`,
				dates: `1748–1837`,
				nationality: `French`,
			},
		],
		date: `ca. 1790`,
		dateBegin: 1790,
		medium: `graphite under pen and black ink with wash on cream antique laid paper`,
		dimensions: `Sheet: 140 x 105 mm (5 1/2 x 4 1/8 in.)`,
		creditLine: `Achenbach Foundation for Graphic Arts`,
		accession: `1963.24.283r-v`,
		accessionDate: `1963`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Drawing`,
		onView: false,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 298 — /artworks/the-assuaging-of-the-waters
	{
		id: `157713`,
		title: `The Assuaging of the Waters`,
		artist: `John Martin`,
		artistDates: `1789–1854`,
		artistNationality: `English`,
		constituents: [
			{
				id: `C-3765`,
				name: `John Martin`,
				role: `Artist`,
				dates: `1789–1854`,
				nationality: `English`,
			},
		],
		date: `1840`,
		dateBegin: 1840,
		dateEnd: 1840,
		medium: `Oil on canvas`,
		dimensions: `56 1/2 x 86 1/4 in. (143.5 x 219.1 cm)`,
		creditLine: `Museum purchase, Whitney Warren Jr. Bequest Fund in memory of Mrs. Adolph B. Spreckels`,
		accession: `1989.73`,
		accessionDate: `1989`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `A biblical narrative presented in the guise of a seascape, this turbulent scene was the concluding image in a trilogy of paintings depicting episodes of the flood recounted in Genesis. Noah’s ark appears miniscule on the horizon, emphasizing the infinitesimal scale of human life on this remade planet. Martin achieved the visionary quality of the painting in part through the impossible viewpoint, situating the viewer on land just reclaimed from the floodwaters. As the ocean recedes, we witness the earth’s surface freshly composed of an assortment of watery and rocky elements, accentuated by Martin’s idiosyncratic application of oil paint, alternatingly fluid and pebbly. The flood had followed God’s decision to cleanse human sinfulness from the earth, and this metaphysical drama plays out symbolically in the painting’s foreground. The dove will return to the ark having plucked an olive branch as proof of dry land. While Genesis does not comment on the raven’s fate, Martin imagines the bird standing over a drowned serpent, alluding to the triumph over Satan and sin. The marine life, however, reveals Martin at his most ingenious. He had a strong inclination toward science and engineering, and his depiction of the spiral-shelled argonaut incorporates a recent biological discovery into this scene of primordial rebirth. In 1839, the London Zoological Society confirmed Jeanne Villepreaux-Powers’s findings that the argonaut did, in fact, produce its own shell, or egg case, with the two sail-like arms that Martin accentuates in his depiction of it. Even as early paleontologists in England were looking to the fossil record to establish Earth’s age, Martin found a metaphor for Noah’s construction of the ark and the safe passage of his family in the burgeoning field of marine biology.`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		placeOfCreation: [`England`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 293 — /artworks/sky-cathedrals-presence-i
	{
		id: `136399`,
		title: `Sky Cathedral's Presence I`,
		artist: `Louise Nevelson`,
		artistDates: `1899–1988`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-6251`,
				name: `Louise Nevelson`,
				role: `Artist`,
				dates: `1899–1988`,
				nationality: `American`,
			},
		],
		date: `1959–1962`,
		dateBegin: 1959,
		dateEnd: 1962,
		medium: `Painted wood and found objects`,
		dimensions: `107 x 120 1/8 x 21 1/2 in. (271.8 x 305.1 x 54.6 cm)`,
		creditLine: `Museum purchase, Phyllis C. Wattis Fund for Major Accessions`,
		accession: `2017.50`,
		accessionDate: `2017`,
		department: `American Decorative Arts and Sculpture`,
		classification: `Sculpture`,
		onView: true,
		labelText: `Louise Nevelson created her wall-size constructions from cast-off wood and metal scavenged from the streets of New York City. Nevelson’s “Sky Cathedral” sculptures were inspired by diverse sources that included ancient Mayan temples, Gothic European cathedrals, and Manhattan’s urban landscape, which she described “as a great big sculpture.” The boxes of fragments in "Sky Cathedral’s Presence I" contain enigmatic signs and symbols that are open to any number of interpretations. Nevelson linked her first use of coffin-like black boxes to the trauma inflicted by World War II, in which her son served. The works in Nevelson’s “Sky Cathedral” series address the issue of religious belief in an existential age wrought by the horrors of war, the Holocaust, and the atomic bomb. Balancing fragmentation and unity, they reflect our perennial desire for something larger than ourselves—a mythical and mysterious “presence” that is spiritually sustaining.`,
		signed: `The artist’s signature – “Nevelson 1964” – appears on component #2.`,
		inscriptions: `Pencil writing reading “P.G. #01963” appears on the back of at least three components (#3, 4, and 7).`,
		identifyingDescription: `The object is a collage relief made of salvaged wooden boxes, wood scraps and objects fragments, spray-painted in black. The whole object consists of eleven components, plus a 2-part base. Each component is identified by a white label with a number (from 1 to 11) glued on its back. A hand drawn diagram, glued under component #11, shows the location of each component. Its numbering system is consistent with the numbers written on the white labels. A different, and probably more recent numbering, appears on blue tape stuck on the back of each component. Pencil writing reading “P.G. #01963” appears on the back of at least three components (#3, 4, and 7). The artist’s signature – “Nevelson 1964” – appears on component #2.`,
		placeOfCreation: [`United States`],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 277 — /artworks/boatmen-on-the-missouri
	{
		id: `73556`,
		title: `Boatmen on the Missouri`,
		artist: `George Caleb Bingham`,
		artistDates: `American, 1811–1879`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-6576`,
				name: `George Caleb Bingham`,
				role: `Artist`,
				dates: `American, 1811–1879`,
				nationality: `American`,
			},
		],
		date: `1846`,
		dateBegin: 1846,
		dateEnd: 1846,
		medium: `Oil on canvas`,
		dimensions: `25 1/8 x 30 1/4 in. (63.8 x 76.8 cm); Frame: 35 3/4 x 40 1/2 x 4 1/2 in. (90.8 x 102.9 x 11.4 cm)`,
		creditLine: `Gift of Mr. and Mrs. John D. Rockefeller 3rd`,
		accession: `1979.7.15`,
		accessionDate: `1979`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `In the nineteenth century, major rivers served as interstate highways for steamboats carrying passengers and cargo. Missouri River steamboats were refueled by “woodhawks,” men in small boats loaded with firewood. George Caleb Bingham’s painting presents these boatmen as mediators between nature, represented by the surrounding wilderness, and civilization, symbolized by the steamboat. Although Bingham’s scene evokes an overall feeling of ease, the surface of the water bubbles behind their raft, and the large branch at the left of the composition suggests the dangers that lie below the river’s surface beyond their view.`,
		placeOfCreation: [`Missouri`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 271 — /artworks/lux-aeterna
	{
		id: `100134`,
		title: `Lux Aeterna`,
		artist: `Gottardo Piazzoni`,
		artistDates: `1872–1945`,
		artistNationality: `American (b. Switzerland)`,
		constituents: [
			{
				id: `C-8818`,
				name: `Gottardo Piazzoni`,
				role: `Artist`,
				dates: `1872–1945`,
				nationality: `American (b. Switzerland)`,
			},
		],
		date: `1914`,
		dateBegin: 1914,
		dateEnd: 1914,
		medium: `Oil on canvas`,
		dimensions: `Overall: 42 1/2 x 60 1/2 x 3 3/8 in. (107.95 x 153.67 x 8.573 cm) Framed: 49 3/16 x 67 1/8 in. (124.9 x 170.5 cm)`,
		creditLine: `Gift in memory of Ethel A. Voorsanger by her friends through the Patrons of Art and Music`,
		accession: `1981.90`,
		accessionDate: `1981`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Google Lens entry:In his study of Piazzoni's life and work, Gene Hailey concluded, "In the narration of Piazzoni's interesting life, the evaluators of his work have played upon the adjectives of beauty and truth, a symphony of heavenly music. Searching for a conclusion, the Lux Aeterna seems fitting. In this painting Piazzoni has epitomized the desire of his life; that of flooding the white-robed figure of truth and beauty, in the effulgence of eternal light." Gottardo Piazzoni was born in Intranga, Switzerland, and he moved with his family to California at the age of fifteen. His father had established a dairy farm in Carmel Valley, and life on the farm taught Piazzoni to revere and respect nature. He studied with Arthur Mathews at the California School of Design, followed by a sojourn in Paris. Piazzoni eventually settled in California, where he developed his mature style, featuring harmonious palettes, spare compositions, and poetic symbolism.`,
		placeOfCreation: [`California`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 266 — /artworks/the-empire-of-flora
	{
		id: `269788`,
		title: `The Empire of Flora`,
		artist: `Giovanni Battista Tiepolo`,
		artistDates: `1696–1770`,
		artistNationality: `Italian`,
		constituents: [
			{
				id: `C-14935`,
				name: `Giovanni Battista Tiepolo`,
				role: `Artist`,
				dates: `1696–1770`,
				nationality: `Italian`,
			},
		],
		date: `ca. 1743`,
		dateBegin: 1738,
		dateEnd: 1748,
		medium: `Oil on canvas`,
		dimensions: `28 1/4 x 35 in. (71.8 x 88.9 cm)`,
		creditLine: `Gift of the Samuel H. Kress Foundation`,
		accession: `61.44.19`,
		accessionDate: `1961`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Tiepolo was the preeminent Italian painter of the eighteenth century. His style is at its most exuberant in this representation of Flora, Roman goddess of flowers and spring. In an inviting garden, under a bright blue sky, Flora rides into the scene on a chariot pulled by winged putti. This picture’s patron was Count Francesco Algarotti, an envoy to the Dresden court of Augustus III. Algarotti commissioned this painting and its pendant (today in the State Hermitage Museum, Saint Petersburg), as gifts for Count Heinrich von Brühl, chief minister to Augustus. The fountain in the background alludes to a public sculpture that Brühl had commissioned, and, writing to Brühl, Algarotti drew a flattering comparison between the transformations brought about by Flora in ancient myth and those brought about by his correspondent in modern Dresden: “The influence of Flora . . . transforms the most savage places into delightful precincts.”`,
		placeOfCreation: [`Venice`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 266 — /artworks/mural-fragments-2
	{
		id: `95262`,
		title: `Untitled`,
		artist: `Teotihuacan`,
		artistDates: `active 3th–8th century`,
		artistNationality: `Mesoamerica`,
		constituents: [
			{
				id: `C-12848`,
				name: `Teotihuacan`,
				role: `Artist`,
				dates: `active 3th–8th century`,
				nationality: `Mesoamerica`,
			},
		],
		date: `300–400`,
		dateBegin: 300,
		dateEnd: 400,
		medium: `Earthen aggregate, lime plaster, and mineral pigments`,
		dimensions: `Overall: 24 x 58 1/16 in. (60.96 x 147.479 cm)`,
		creditLine: `Bequest of Harald J. Wagner`,
		accession: `1985.104.12`,
		accessionDate: `1985`,
		department: `Arts of Africa, Oceania, and the Americas`,
		classification: `Architectural Element`,
		onView: true,
		culture: `Teotihuacan`,
		identifyingDescription: `Mural fragment with coyotes and deer`,
		placeOfCreation: [`Teotihuacan`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 264 — /artworks/dinner-for-threshers
	{
		id: `115286`,
		title: `Dinner for Threshers`,
		artist: `Grant Wood`,
		artistDates: `1891–1942`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-3155`,
				name: `Grant Wood`,
				role: `Artist`,
				dates: `1891–1942`,
				nationality: `American`,
			},
		],
		date: `1934`,
		dateBegin: 1934,
		dateEnd: 1934,
		medium: `Oil on hardboard`,
		dimensions: `20 x 80 in. (50.8 x 203.2 cm)`,
		creditLine: `Gift of Mr. and Mrs. John D. Rockefeller 3rd`,
		accession: `1979.7.105`,
		accessionDate: `1979`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `As the figures’ outdated clothes suggest, "Dinner for Threshers" was inspired by Grant Wood’s childhood memories of the annual threshing ritual on his family’s Iowa farm. This important economic and social event involved harvesting the winter wheat or oat crop and then separating the kernels of grain from the straw stalks and seed casings. While men and boys worked in the field, women and girls worked in the kitchen preparing the harvest lunch (“dinner” in the Midwest). Wood’s cutaway view of an Iowa farmhouse interior recalls early Renaissance paintings depicting the Last Supper of Christ and his apostles. This historical precedent endows the modern farmers with the dignity of biblical disciples participating in a sacred meal. It also enabled Wood to avoid depicting the economic devastation of the Great Depression, which included a prolonged drought and farm failures that ran as high as twenty-five percent in parts of Iowa in the early 1930s.`,
		placeOfCreation: [`United States`],
		copyrightStatus: `in-copyright`,
	},
	// GA views (90d): 260 — /artworks/california-spring
	{
		id: `1402`,
		title: `California Spring`,
		artist: `Albert Bierstadt`,
		artistDates: `American, born Germany, 1830–1902`,
		artistNationality: `American, b. Germany`,
		constituents: [
			{
				id: `C-7647`,
				name: `Albert Bierstadt`,
				role: `Artist`,
				dates: `American, born Germany, 1830–1902`,
				nationality: `American, b. Germany`,
			},
		],
		date: `1875`,
		dateBegin: 1875,
		dateEnd: 1875,
		medium: `Oil on canvas`,
		dimensions: `54 1/2 x 84 1/4 in. (138.43 x 213.995 cm)`,
		creditLine: `Presented to the City and County of San Francisco by Gordon Blanding`,
		accession: `1941.6`,
		accessionDate: `1941`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Albert Bierstadt's California Spring was based on sketches he made while visiting the San Francisco Bay Area (1871-1873). This lush view of the Sacramento River Valley would have convinced viewers—and potential settlers—that California was suitable for both habitation and cultivation. California's actual climate was satirized in Bret Harte's poem “California Madrigal: On the Approach of Spring” (ca. 1871): "Oh come, my beloved! from thy winter abode, From thy home on the Yuba, thy ranch overflowed; For the waters have fallen, the winter has fled, And the river once more has returned to its bed. Then fly with me, love, ere the summer's begun, And the mercury mounts to one hundred and one; Ere the grass now so green shall be withered and sear, In the spring that obtains but one month in the year." [Bret Harte, East and West (Whitefish, MT: Kessinger Publishing, 2004, 65.]`,
		inscriptions: `Signed lower right: ABierstadt`,
		placeOfCreation: [`California`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 250 — /artworks/tulip-culture
	{
		id: `212718`,
		title: `Tulip Culture`,
		artist: `George Hitchcock`,
		artistDates: `1850–1913`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-17600`,
				name: `George Hitchcock`,
				role: `Artist`,
				dates: `1850–1913`,
				nationality: `American`,
			},
		],
		date: `1889`,
		dateBegin: 1889,
		dateEnd: 1889,
		medium: `Oil on canvas`,
		dimensions: `44 3/4 x 65 1/2 in. (113.7 x 166.4 cm); Frame: 55 3/16 x 74 x 3 in. (140.2 x 188 x 7.6 cm)`,
		creditLine: `Gift of Diane B. Wilsey in honor of the tenth anniversary of the new de Young museum`,
		accession: `2016.25`,
		accessionDate: `2016`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Google Lens entry:In 1883, the American expatriate painter Hitchcock settled in Holland, making his home near Egmond aan Zee, which he helped transform into a significant artist colony. Inspired by the “symphonies of color” he found in the Dutch landscape, Hitchcock later publishing a series of articles titled, “The Picturesque Quality of Holland,” in which he praised “the mysterious, endless fields…the opulence of tone and color; the unity and mystery of the vast meadows.”George Hitchcock grew up in Rhode Island, attended Brown University, and studied law at Harvard. Just a few short years after being admitted to the bar in Providence and New York, he abandoned law for art, going abroad to study with renowned teachers, like Gustave Boulanger and Jules Lefebvre in Paris and Hendrik Willem Mesdag in the Hague. By 1883, Hitchcock had settled in Holland, making his home near the small village of Egmond aan Zee, which he helped to transform into a significant art colony.-----10/6/15In 1883, the American expatriate painter George Hitchcock settled in Holland, making his home near Egmond aan Zee, which he helped transform into a significant artist colony. Inspired by the “symphonies of color” he found in the Dutch landscape, Hitchcock later publishing a series of articles titled, “The Picturesque Quality of Holland,” in which he praised “the mysterious, endless fields…the opulence of tone and color; the unity and mystery of the vast meadows.”-----Poets in the Galleries:Reaching Upby Sierra Barnes, 5th grade, Wagner Ranch Elementary SchoolThe people call me beautiful, for I light up in the morning's warm sky with my velvet pink reaching to youlike a best friend.For now it is spring and I grow tall, and you reach for me.Grabbing our dew covered stems, picking everyone, being careful not to drop us.But I keep blooming, soft as cotton candy and still as the wind.`,
		placeOfCreation: [`Holland`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 248 — /artworks/sailboats-on-the-seine-at-petit-gennevilliers
	{
		id: `28078`,
		title: `Sailboats on the Seine at Petit-Gennevilliers`,
		artist: `Claude Monet`,
		artistDates: `French, 1840–1926`,
		artistNationality: `French`,
		constituents: [
			{
				id: `C-6087`,
				name: `Claude Monet`,
				role: `Artist`,
				dates: `French, 1840–1926`,
				nationality: `French`,
			},
		],
		date: `1874`,
		dateBegin: 1874,
		dateEnd: 1874,
		medium: `Oil on canvas`,
		dimensions: `Overall: 21 3/8 x 25 3/4 in. (54.293 x 65.4 cm) Framed: 30 3/16 x 34 5/8 in. (76.676 x 87.948 cm) - Glazed`,
		creditLine: `Gift of Bruno and Sadie Adriani`,
		accession: `1962.23`,
		accessionDate: `1962`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Painted outdoors in the year of the first Impressionist group exhibition, this work depicts pleasure boats moored on the Seine at Petit-Gennevilliers, a suburb of Paris, where sailing was popularized from the mid-nineteenth century. The view seems to be from a position on the water, and it has been suggested that this canvas is the picture seen on the easel in Édouard Manet’s famous Monet Painting in His Studio Boat (1874, Munich, Neue Pinakothek).`,
		placeOfCreation: [`Gennevilliers`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 241 — /artworks/saint-francis-venerating-the-crucifix
	{
		id: `285113`,
		title: `Saint Francis Venerating the Crucifix`,
		artist: `Domenikos Theotokopoulos (El Greco)`,
		artistDates: `Greek, active Spain, 1541 - 1614`,
		artistNationality: `Greek, active Spain`,
		constituents: [
			{
				id: `C-3271`,
				name: `Domenikos Theotokopoulos (El Greco)`,
				role: `Artist`,
				dates: `Greek, active Spain, 1541 - 1614`,
				nationality: `Greek, active Spain`,
			},
		],
		date: `ca. 1595`,
		dateBegin: 1590,
		dateEnd: 1600,
		medium: `Oil on canvas`,
		dimensions: `58 x 41 1/2 in. (147.3 x 105.4 cm) Framed: 69 1/2 x 53 in. (176.53 x 134.62 cm)`,
		creditLine: `Gift of the Samuel H. Kress Foundation`,
		accession: `61.44.24`,
		accessionDate: `1961`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Saint Francis of Assisi (1181/82-1226) was a popular subject for artists during the late sixteenth and early seventeenth centuries, and El Greco painted the saint repeatedly. Here he has depicted Saint Francis meditating on the subject of Christ’s sacrifice, referenced by the crucifix, skull, and bible. The great rock in the background suggests Mount Alverna in central Italy, where it is believed the saint received the stigmata.`,
		placeOfCreation: [`Spain`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 238 — /artworks/under-the-wave-off-kanagawa-the-great-wave-from-the-series-thirty-six-views-of-mount-fuji
	{
		id: `97583`,
		title: `Under the Wave off Kanagawa (The Great Wave), from the series Thirty-Six Views of Mount Fuji`,
		artist: `Katsushika Hokusai`,
		artistDates: `Japanese, 1760–1849`,
		artistNationality: `Japanese`,
		constituents: [
			{
				id: `C-2336`,
				name: `Katsushika Hokusai`,
				role: `Artist`,
				dates: `Japanese, 1760–1849`,
				nationality: `Japanese`,
			},
			{
				id: `C-4186`,
				name: `Nishimuraya Yohachi (Eijudo)`,
				role: `Publisher`,
				dates: `Japanese`,
				nationality: `Japanese`,
			},
		],
		date: `ca. 1830–1832`,
		dateBegin: 1825,
		dateEnd: 1837,
		medium: `Color woodblock print`,
		dimensions: `9 13/16 x 14 1/2 in. (25 x 36.9 cm) Image: 9 13/16 x 14 7/16 in. (25 x 36.6 cm)`,
		creditLine: `Museum purchase, Achenbach Foundation for Graphic Arts Endowment Fund`,
		accession: `1969.32.6`,
		accessionDate: `1969`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Print`,
		onView: false,
		labelText: `Perhaps the single most iconic image of the ukiyo-e period, this print shows the sacred mountain--Mount Fuji, in the distance, across the trough of a great wave. The precarious intermingling of boats and crashing waves in the foreground has led some to interpret the composition as bringing together three primary elements of lived experience: the human, the terrestrial, and the divine Karin Breuer, Japanesque (2010).`,
		identifyingDescription: `Great wave occupies half the surface; 2 long boats shaped to fit the wave; Mt. Fuji in distance.`,
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 231 — /artworks/the-great-statue-of-amida-buddha-at-kamakura
	{
		id: `111335`,
		title: `The Great Statue of Amida Buddha at Kamakura`,
		artist: `John La Farge`,
		artistDates: `1835–1910`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-965`,
				name: `John La Farge`,
				role: `Artist`,
				dates: `1835–1910`,
				nationality: `American`,
			},
		],
		date: `ca. 1887`,
		dateBegin: 1882,
		dateEnd: 1892,
		medium: `Watercolor over graphite on wove paper`,
		dimensions: `15 15/16 x 19 3/8 in. (40.5 x 49.2 cm) (irregular)`,
		creditLine: `Gift of Mr. and Mrs. John D. Rockefeller 3rd`,
		accession: `1979.7.70`,
		accessionDate: `1979`,
		department: `Achenbach Foundation for Graphic Arts`,
		classification: `Drawing`,
		onView: false,
		identifyingDescription: `side view of the upper portion of the figure of the statue of the seated Buddha at Kamakura with trees, temple roofs, hillside`,
		images: [
			{
				label: `Primary view`,
				altText: ``,
			},
		],
		placeOfCreation: [`United States`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 230 — /artworks/flowers-in-a-silver-vase
	{
		id: `187097`,
		title: `Flowers in a Silver Vase`,
		artist: `Willem van Aelst`,
		artistDates: `Dutch, 1627-after 1687`,
		artistNationality: `Dutch`,
		constituents: [
			{
				id: `C-17380`,
				name: `Willem van Aelst`,
				role: `Artist`,
				dates: `Dutch, 1627-after 1687`,
				nationality: `Dutch`,
			},
		],
		date: `1663`,
		dateBegin: 1663,
		medium: `Oil on canvas`,
		dimensions: `26 5/8 x 21 1/2 in. (67.6 x 54.6 cm) Framed: 36 x 30 7/8 in. (91.44 x 78.423 cm)`,
		creditLine: `Gift of Dr. and Mrs. Hermann Schuelein`,
		accession: `51.21`,
		accessionDate: `1951`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Willem van Aelst initially trained and became a master in his native Delft, then traveled to France and Italy, before ultimately settling in Amsterdam. The Italian spelling of his name, used for the signature of this and other post-Italian period paintings, adds a veneer of distinction and suggests these foreign experiences and contacts, most particularly his association with foreign patrons, including Ferdinand II de’ Medici, Grand Duke of Tuscany. As there are layers of significance to the artist’s signature, so the imagery and meaning of this flowerpiece is artfully layered. In an apparently informal profusion of blooms and foliage, the artist carefully constructs a dynamic Baroque composition. Dramatic lighting is choreographed to emphasize the principal blooms, creating a diagonal across the picture’s surface. Equally Baroque is the activation of the entire scene, beyond the objects’ actual potential for movement. This is achieved by an insistence on the irregularity of the organic forms, which curve and countercurve out of the back into the mass of the bouquet. Despite the gaiety of this floral arrangement, several traditional symbols of time’s fleeting nature are included. Note the tattered ribbons of the open watchcase and the fully opened tulip, ready to drop its petals. Such allusions to the transience of life and beauty invest this seemingly straightforward still life with a moralizing aspect, transforming it into a vanitas still life, an essay on the vanity of life.`,
		signed: `Guill mo van Aelst 1663`,
		placeOfCreation: [`Netherlands`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 229 — /artworks/the-calling-of-saint-matthew
	{
		id: `114005`,
		title: `The Calling of Saint Matthew`,
		artist: `Matthias Stomer`,
		artistDates: `1600–1650`,
		artistNationality: `Dutch`,
		constituents: [
			{
				id: `C-16789`,
				name: `Matthias Stomer`,
				role: `Artist`,
				dates: `1600–1650`,
				nationality: `Dutch`,
			},
		],
		date: `ca. 1629`,
		dateBegin: 1624,
		dateEnd: 1634,
		medium: `Oil on canvas`,
		dimensions: `69 x 88 1/4 in. (175.26 x 224.155 cm) Framed: 81 7/8 x 101 5/8 in. (207.963 x 258.128 cm)`,
		creditLine: `Museum purchase, Roscoe and Margaret Oakes Income Fund`,
		accession: `1986.27`,
		accessionDate: `1986`,
		department: `European Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Born in Amersfoort, near Utrecht, Matthias Stom is among the scores of seventeenth-century Northern artists who made their way to Italy in search of firsthand knowledge of the art of both the past and the present. The hallmark of Stom’s art is his personal interpretation of the Caravaggesque vocabulary, learned initially from Dutch artists working in Utrecht and strengthened in Rome, Naples, and Sicily by direct exposure to Caravaggio’s works. Ultimately based on Caravaggio’s painting of the same subject executed thirty years earlier for the church of San Luigi dei Francesi in Rome, Stom’s Calling of Saint Matthew is a tour de force of baroque internalized drama and compositional sophistication. Stom employs a number of formal devices popularized by Caravaggio: sharp light-dark contrasts, which create a theatrical play of light across the forms; careful attention to realistic detail and surface textures; and, most significant, the interpretation of sacred events in terms of everyday life, acted out by ordinary people. The painting illustrates the moment when Christ challenges the Roman tax collector Levi to forsake the privileges of his imperial post to “Follow me” (Luke 5:27-28). Levi, the man seated at the far right, will indeed follow Jesus’ lead and will thereafter be known as the apostle Matthew. The psychological tie between Jesus and Levi, to which the attending figures seem largely oblivious, is reinforced by the coloration of their two costumes. Similar shades of red and blue frame the scene like parentheses and redirect the attention to the center of the figural group. There the grouping of hands, book, and scales is a virtuoso display of convincing spatial effects. -Lynn Federle Orr, Masterworks of European Painting in the California Palace of the Legion of Honor (1999)`,
		placeOfCreation: [`Netherlands`],
		copyrightStatus: `copyright-unknown`,
	},
	// GA views (90d): 229 — /artworks/the-blue-veil
	{
		id: `41545`,
		title: `The Blue Veil`,
		artist: `Edmund Charles Tarbell`,
		artistDates: `1862–1938`,
		artistNationality: `American`,
		constituents: [
			{
				id: `C-405`,
				name: `Edmund Charles Tarbell`,
				role: `Artist`,
				dates: `1862–1938`,
				nationality: `American`,
			},
		],
		date: `1898`,
		dateBegin: 1898,
		dateEnd: 1898,
		medium: `Oil on canvas`,
		dimensions: `29 x 24 in. (73.7 x 61 cm) Framed: 34 x 29 in. (86.4 x 73.7 cm)`,
		creditLine: `Gift of Henry K.S. Williams`,
		accession: `1942.26`,
		accessionDate: `1942`,
		department: `American Paintings`,
		classification: `Painting`,
		onView: true,
		labelText: `Google Lens entry: As the title makes clear, Tarbell's painting is not about his sitter. Rather, it is a painting of her veil, which has been caught by a breeze and flows around her face and shoulders in sheer folds and waves. Throughout his life and career, Tarbell was both praised and criticized for his single-minded commitment to beauty. In response to his critics, he said, "Art should render the beauty of the thing seen.” Edmund Tarbell was one of the most acclaimed artists in Boston at the turn of the century. Raised in West Groton, Massachusetts, his artistic talent was recognized when he enrolled as an art student at the School of the Museum of Fine Arts, where he was made the head of painting at just 27 years old. Tarbell adopted an impressionist style after completing his studies in Boston and Paris. By the 1890s, he became a founding member of the Ten, a group at the forefront of American Impressionism. --------------- (Untitled) by Jonah Copi, 7th grade, The San Francisco School I shift and change places with her every move. I glide, flowing in the air with the slightest gust of wind. I hide her beauty and insure her innocence. I conceal her emotions with my blue shadow and act as her barrier. It is my duty to protect her and I do my best. She is helpless without my blue, silky shield The two of us become one as I cling to her forever. I give her clarity in a state of confusion. I give her guidance in a time of fogginess. I am not only her veil but her friend and protector. Alternative label: LP for Google Lens, April 2018: As the title makes clear, Tarbell's painting is not about his sitter. Rather, it is a painting of her veil, which has been caught by a breeze and flows around her face and shoulders in sheer folds and waves. Throughout his life and career, Tarbell was both praised and criticized for his single-minded commitment to beauty. In response to his critics, he said, "Art should render the beauty of the thing seen.”`,
		placeOfCreation: [`United States`],
		copyrightStatus: `copyright-unknown`,
	},
];
