import Container from "@/components/wireframe/Container";
import SectionLabel from "@/components/wireframe/SectionLabel";
import WireframeSection from "@/components/wireframe/WireframeSection";
import schemaData from "@/data/schema.json";
import LineageTable, { type FieldRow } from "./LineageTable";

interface SchemaDoc {
	generated_at: string;
	pipeline_rev: string;
	schema_strict: boolean;
	field_count: number;
	lineage_resolved_count: number;
	passthrough_count: number;
	derived_count: number;
	unknown_count: number;
	multi_source_count: number;
	fields: FieldRow[];
}

const data = schemaData as SchemaDoc;

export default function SchemaReferencePage() {
	const lineagePct = Math.round(
		(data.lineage_resolved_count / data.field_count) * 100,
	);

	return (
		<div className="min-h-screen bg-white">
			<WireframeSection
				label="Header"
				className="border-b border-gray-300 py-6"
			>
				<Container>
					<SectionLabel>Pipeline introspection</SectionLabel>
					<h1 className="mt-1 font-mono text-2xl text-gray-900">
						Schema Reference
					</h1>
					<p className="mt-2 max-w-3xl font-mono text-meta text-gray-600">
						Every ES field in the FAMSF collection-document shape, with upstream
						column lineage from the Dagster pipeline. Generated by the{" "}
						<code className="bg-gray-100 px-1">schema_doc</code> asset
						(collection-flow-famsf), which reads{" "}
						<code className="bg-gray-100 px-1">dagster/column_lineage</code>{" "}
						metadata from{" "}
						<code className="bg-gray-100 px-1">collection_documents</code> and
						merges with{" "}
						<code className="bg-gray-100 px-1">CollectionSchema</code> (pandera)
						and <code className="bg-gray-100 px-1">ES_MAPPING</code>.
					</p>
					<p className="mt-2 font-mono text-meta text-gray-500">
						Generated{" "}
						{new Date(data.generated_at).toLocaleString("en-GB", {
							day: "numeric",
							month: "short",
							year: "numeric",
							hour: "2-digit",
							minute: "2-digit",
						})}{" "}
						from pipeline rev{" "}
						<code className="bg-gray-100 px-1">{data.pipeline_rev}</code>
					</p>

					<div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-5">
						<div className="border border-gray-300 p-3">
							<div className="font-mono text-2xl text-gray-900">
								{data.field_count}
							</div>
							<SectionLabel>ES fields</SectionLabel>
						</div>
						<div className="border border-gray-300 p-3">
							<div className="font-mono text-2xl text-gray-900">
								{data.lineage_resolved_count}
							</div>
							<SectionLabel>With lineage ({lineagePct}%)</SectionLabel>
						</div>
						<div className="border border-gray-300 p-3">
							<div className="font-mono text-2xl text-gray-700">
								{data.passthrough_count}
							</div>
							<SectionLabel>Passthrough</SectionLabel>
						</div>
						<div className="border border-gray-300 p-3">
							<div className="font-mono text-2xl text-amber-700">
								{data.derived_count}
							</div>
							<SectionLabel>Derived</SectionLabel>
						</div>
						<div className="border border-gray-300 p-3">
							<div className="font-mono text-2xl text-purple-700">
								{data.multi_source_count}
							</div>
							<SectionLabel>Multi-source</SectionLabel>
						</div>
					</div>
				</Container>
			</WireframeSection>

			<WireframeSection label="Lineage table" className="py-6">
				<Container>
					<LineageTable fields={data.fields} />
				</Container>
			</WireframeSection>

			<WireframeSection label="Notes" className="border-t border-gray-300 py-6">
				<Container>
					<SectionLabel>How lineage gets here</SectionLabel>
					<ol className="mt-2 max-w-3xl list-decimal space-y-1 pl-5 font-mono text-meta text-gray-700">
						<li>
							<code className="bg-gray-100 px-1">collection_documents</code>{" "}
							asset returns{" "}
							<code className="bg-gray-100 px-1">dg.Output[pl.LazyFrame]</code>{" "}
							with{" "}
							<code className="bg-gray-100 px-1">dagster/column_lineage</code>{" "}
							metadata listing each output column's upstream dep.
						</li>
						<li>
							<code className="bg-gray-100 px-1">schema_doc</code> asset reads
							that metadata from the latest materialization event and walks
							backwards through each upstream asset's own lineage to reach the
							TMS source table. Merges with{" "}
							<code className="bg-gray-100 px-1">CollectionSchema</code>{" "}
							(pandera) and <code className="bg-gray-100 px-1">ES_MAPPING</code>
							.
						</li>
						<li>
							Dual-writes to wireframe repo via{" "}
							<code className="bg-gray-100 px-1">
								COLFLOW_WIREFRAMES_SCHEMA_PATH
							</code>{" "}
							env var. Auto-refreshes on every pipeline run.
						</li>
						<li>
							Multi-source columns walk via first dep; tagged{" "}
							<code className="bg-gray-100 px-1">(+N more sources)</code>.
							Consecutive same-column passthroughs collapse to one hop tagged{" "}
							<code className="bg-gray-100 px-1">(+N unchanged hops)</code>.
						</li>
					</ol>
				</Container>
			</WireframeSection>
		</div>
	);
}
